AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NorthStar Agentic AI - Lambda Backend

Globals:
  Function:
    Runtime: python3.12
    Timeout: 15
    MemorySize: 256

Parameters:
  BucketName:
    Type: String
    Description: S3 bucket containing insurance data

  ClaimsPrefix:
    Type: String
    Description: S3 prefix for claims data

  InsuranceDataPrefix:
    Type: String
    Description: S3 prefix for policies and rules data

Resources:

  #########################################
  # Get Policy Details Lambda
  #########################################

  GetPolicyDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: agent-get-policy-details
      CodeUri: get_policy_details/
      Handler: app.lambda_handler
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          DATA_PREFIX: !Ref InsuranceDataPrefix
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BucketName

  #########################################
  # Check Document Requirements Lambda
  #########################################

  CheckDocumentRequirementsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: agent-check-document-requirements
      CodeUri: check_document_requirements/
      Handler: app.lambda_handler
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          DATA_PREFIX: !Ref InsuranceDataPrefix
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BucketName

  #########################################
  # Get Claim Status Lambda
  #########################################

  GetClaimStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: agent-get-claim-status
      CodeUri: get_claim_status/
      Handler: app.lambda_handler
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          CLAIMS_PREFIX: !Ref ClaimsPrefix
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BucketName

  #########################################
  # Agent Orchestrator Lambda
  #########################################

  AgentOrchestratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: northstar-agent-orchestrator
      CodeUri: agent_orchestrator/
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          GET_POLICY_FUNCTION: agent-get-policy-details
          CHECK_DOC_FUNCTION: agent-check-document-requirements
          GET_CLAIM_FUNCTION: agent-get-claim-status
      Policies:
        - LambdaInvokePolicy:
            FunctionName: agent-get-policy-details
        - LambdaInvokePolicy:
            FunctionName: agent-check-document-requirements
        - LambdaInvokePolicy:
            FunctionName: agent-get-claim-status
      Events:
        AgentApi:
          Type: Api
          Properties:
            Path: /agent
            Method: post
  
Outputs:

  GetPolicyDetailsFunctionArn:
    Description: ARN of GetPolicyDetails Lambda
    Value: !GetAtt GetPolicyDetailsFunction.Arn

  CheckDocumentRequirementsFunctionArn:
    Description: ARN of CheckDocumentRequirements Lambda
    Value: !GetAtt CheckDocumentRequirementsFunction.Arn

  GetClaimStatusFunctionArn:
    Description: ARN of GetClaimStatus Lambda
    Value: !GetAtt GetClaimStatusFunction.Arn
