AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Agentic AI - Lambda Backend

Globals:
  Function:
    Runtime: python3.12
    Timeout: 15
    MemorySize: 256

Parameters:
  BucketName:
    Type: String
    Description: S3 bucket containing insurance data

  ClaimsPrefix:
    Type: String
    Description: S3 prefix for claims data

  InsuranceDataPrefix:
    Type: String
    Description: S3 prefix for policies and rules data
    
  BedrockRouterModel:
    Type: String
    Description: BedRock Model to be used in Agent
    
  BedrockSynthModel:
    Type: String
    Description: Bedock Model to Synth the response
  
  BedrockFallbackModel:
    Type: String
    Description: Fallback Model for Agent
  
  GetPolicyFunction:
    Type: String
    Description: Policy Lambda Function
  
  CheckDocFunction:
    Type: String
    Description: Check Doc Lambda Function
  
  GetClaimFunction:
    Type: String
    Description: Get Claim Lambda Function
    
  DynamoTable:
    Type: String
    Description: DymanoDB Storage for LLM Response

Resources:

  #########################################
  # Get Policy Details Lambda
  #########################################

  GetPolicyDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: agent-get-policy-details
      CodeUri: get_policy_details/
      Handler: app.lambda_handler
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          DATA_PREFIX: !Ref InsuranceDataPrefix
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BucketName

  #########################################
  # Check Document Requirements Lambda
  #########################################

  CheckDocumentRequirementsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: agent-check-document-requirements
      CodeUri: check_document_requirements/
      Handler: app.lambda_handler
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          DATA_PREFIX: !Ref InsuranceDataPrefix
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BucketName

  #########################################
  # Get Claim Status Lambda
  #########################################

  GetClaimStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: agent-get-claim-status
      CodeUri: get_claim_status/
      Handler: app.lambda_handler
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          CLAIMS_PREFIX: !Ref ClaimsPrefix
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BucketName

  #########################################
  # Agent Orchestrator Lambda
  #########################################

  AgentOrchestratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: agent-orchestrator
      CodeUri: agent_orchestrator/
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          AWS_BEDROCK_ROUTER_MODEL: !Ref BedrockRouterModel
          AWS_BEDROCK_SYNTH_MODEL: !Ref BedrockSynthModel
          AWS_BEDROCK_FALLBACK_MODEL: !Ref BedrockFallbackModel
          GET_POLICY_FUNCTION: !Ref GetPolicyDetailsFunction
          CHECK_DOC_FUNCTION: !Ref CheckDocumentRequirementsFunction
          GET_CLAIM_FUNCTION: !Ref GetClaimStatusFunction
          CONVERSATION_TABLE: !Ref DynamoTable
      Policies:
        - LambdaInvokePolicy:
            FunctionName: agent-get-policy-details
        - LambdaInvokePolicy:
            FunctionName: agent-check-document-requirements
        - LambdaInvokePolicy:
            FunctionName: agent-get-claim-status
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoTable
        - Statement:
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
              - bedrock:InvokeModelWithResponseStream
            Resource: "*"
      Events:
        AgentApi:
          Type: Api
          Properties:
            Path: /agent
            Method: post

  #########################################
  # Dynamo DB for Conversations
  #########################################

  ConversationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: northstar-conversations
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
  
Outputs:

  GetPolicyDetailsFunctionArn:
    Description: ARN of GetPolicyDetails Lambda
    Value: !GetAtt GetPolicyDetailsFunction.Arn

  CheckDocumentRequirementsFunctionArn:
    Description: ARN of CheckDocumentRequirements Lambda
    Value: !GetAtt CheckDocumentRequirementsFunction.Arn

  GetClaimStatusFunctionArn:
    Description: ARN of GetClaimStatus Lambda
    Value: !GetAtt GetClaimStatusFunction.Arn
